### ISSUE TITLE
http:// wrapper is disabled in the server configuration

### ISSUE THREAD

**Issue by Rossie** [snaptortoise/wordpress-quick-install#1]
Warning: file_get_contents(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /var/www/virtual/xxx.com/xxx/htdocs/wp-quick-install/index.php on line 84

**Comment by georgemandis** [comment]
Hi Rossie,

What were you doing when you go this error? It looks like it originated from a PHP script. The script as I've set it up is designed to be run from the terminal:

`curl https://raw.github.com/snaptortoise/wordpress-quick-install/master/wordpress | sh`

**Comment by Rossie** [comment]
Hi George!

I just realized I post it to the wrong git issure, this error came up with
an other wp installer called WP-Quick-Install.
Sorry.
I am not able to run your script because on my ISP there is no terminal
sadly.

Gergely.


2017-02-10 22:44 GMT+01:00 George Mandis <notifications@github.com>:

**Comment by georgemandis** [comment]
No worries!
